### ISSUE TITLE
[Feature] Rename repo to include ERC 4626

### ISSUE THREAD

**Issue by CjHare** [CjHare/Separate-Staking-Reward-ERC4626-Vault#22]
## Feature Description

Rename the GitHub repo to include the term ERC 4626

## Additional Information

The vault being a specialization of the ERC4626 implementation, including that term in the title gives a better intuitive description.

**Comment by tempe-techie** [comment]
Do you already have some ideas for the name? As you said, it should include "erc-4626" in the name, but maybe also hint on using separate tokens (a staking token being different from the reward token).

So something like "erc-4626-separate-tokens" or "erc-4626-different-tokens"... Is there any other synonym that could be used instead?

**Comment by CjHare** [comment]
Currently thinking....

`Stake-Rewarding-ERC4626-Vault`

...finding a succinct yet descriptive name is often a challenge 🤔

**Comment by tempe-techie** [comment]
Maybe it's worth asking ChatGPT for some ideas 😅

**Comment by CjHare** [comment]
Renamed to `Separate-Staking-Reward-ERC4626-Vault`
